#!/bin/bash
clear
RED='\E[1;31m'
GREEN='\E[1;32m'
YELLOW='\E[1;33m'
BLUE='\E[1;34m'
PURPLE='\E[1;35m'
CYAN='\E[1;36m'
WHITE='\E[1;37m'
cRES='\E[0m'
dockerComposeVer_reserved="1.29.2"



installDocker(){
local debianCodename
debianCodename=$( . /etc/os-release && printf '%s' "$VERSION_CODENAME" )
install -m 0644 -D /dev/null /etc/apt/keyrings/docker.asc
curl -fsSL https://mirrors.ustc.edu.cn/docker-ce/linux/debian/gpg -o /etc/apt/keyrings/docker.asc || return 1
rm -f /etc/apt/sources.list.d/docker.list
cat << EOF >/etc/apt/sources.list.d/docker.sources
Types: deb
URIs: https://mirrors.ustc.edu.cn/docker-ce/linux/debian
Suites: $debianCodename
Components: stable
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/docker.asc
EOF

unset aptPKG
[[ -z $(dpkg -l | awk '{print$2}' | grep '^docker-ce$') ]] && aptPKG+=(docker-ce)
[[ -z $(dpkg -l | awk '{print$2}' | grep '^docker-ce-cli$') ]] && aptPKG+=(docker-ce-cli)
[[ -z $(dpkg -l | awk '{print$2}' | grep '^containerd.io$') ]] && aptPKG+=(containerd.io)
if [[ -n $aptPKG ]]; then
apt-get -o Acquire::Retries=2 -o Acquire::ForceIPv4=true -o Acquire::http::Timeout=30 -o Acquire::https::Timeout=30 -o Acquire::http::Pipeline-Depth=0 -o Acquire::https::Pipeline-Depth=0 update -o APT::Update::Error-Mode=any || return 1
apt-get -o Acquire::Retries=2 -o Acquire::ForceIPv4=true -o Acquire::http::Timeout=30 -o Acquire::https::Timeout=30 -o Acquire::http::Pipeline-Depth=0 -o Acquire::https::Pipeline-Depth=0 install -y $(echo ${aptPKG[@]}) || return 1
fi

if [[ -n $(dpkg -l | awk '{print$2}' | grep '^docker-ce$') ]] && [[ -n $(dpkg -l | awk '{print$2}' | grep '^containerd.io$') ]]; then
mkdir -p /etc/docker/
systemctl stop docker containerd
cat << EOF >/etc/docker/daemon.json
{
  "iptables": false
}
EOF
systemctl restart docker
fi

dockerComposeVer=$(curl -fsSL "https://api.github.com/repos/docker/compose/releases/latest" | jq -r .tag_name | grep -v '^null$')
[[ -z $dockerComposeVer_reserved ]] && dockerComposeVer=$dockerComposeVer_reserved

curl -L https://github.com/docker/compose/releases/download/$dockerComposeVer/docker-compose-$(uname -s)-$(uname -m) >/usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

echo -e "${WHITE}[ ${GREEN}✓ ${WHITE}]\c" && echo -e "\t${WHITE}Install Docker${cRES}"
}



uninstallDocker(){
rm -f /etc/apt/sources.list.d/docker.list /etc/apt/sources.list.d/docker.sources
apt remove --purge docker-ce docker-ce-cli containerd.io
rm -rf /usr/local/bin/docker-compose

echo -e "${WHITE}[ ${GREEN}✓ ${WHITE}]\c" && echo -e "\t${WHITE}Uninstall Docker${cRES}"
}



start_menu(){
    echo -e "${GREEN}=============================== ${cRES}"
    echo -e "${GREEN}         Docker${cRES}"
    echo -e "${GREEN}=============================== ${cRES}"
    echo -e "${GREEN}1. Install Docker${cRES}"
   echo -e "${YELLOW}2. Uninstall Docker${cRES}"
    echo ""
    read -p "Select:" num
    case "$num" in
    1)
    installDocker
    start_menu
    ;;
    2)
    uninstallDocker
    start_menu
    ;;
    *)
    clear
    echo -e "${RED}Wrong number${cRES}"
    sleep 1s
    start_menu
    ;;
    esac
}

start_menu
