#!/bin/bash
nodeSM_sites=(openai claude gemini grok wikipedia reddit github discord telegram twitter)

for site in ${nodeSM_sites[@]}; do
tag="nodeSM$site"
domain=$(jq -r ".outbounds[] | select(.tag == \"$tag\") | .settings.vnext[0].address" /opt/de_GWD/vtrui/config.json 2>/dev/null | grep -v '^null$')
port=$(jq -r ".outbounds[] | select(.tag == \"$tag\") | .settings.vnext[0].port" /opt/de_GWD/vtrui/config.json 2>/dev/null | grep -v '^null$')

if [[ $port = "443" ]]; then
nodecheck=$domain
else
nodecheck="$domain:$port"
fi

checkNum=$(jq -r --arg nodecheck $nodecheck '.v2node | to_entries[] | select(.value.domain == $nodecheck) | .key' /opt/de_GWD/0conf)
checkName=$(jq -r --arg nodecheck $nodecheck '.v2node[] | select(.domain == $nodecheck) | .name' /opt/de_GWD/0conf)

if [[ -z $checkNum ]]; then
echo "0"
else
echo $((checkNum+=1))
fi

if [[ -z $checkName ]]; then
echo "-none-"
else
echo $checkName
fi
done
